[Feat/#4]: 게시글 API 기능 구현
Team-DevHub/dev-hub-back pull request #6
Opened 2024-05-18 06:38 UTC by kkang0

## 📍 작업 내용

이번 PR에서 작업한 내용을 간략히 설명해주세요.
- postController.js 게시글 작성, 게시글 조회, 게시글 상세 조회, 게시글 삭제 기능 구현
- postService.js 파일에서 위의 모든 게시글 서비스 로직 구현
- postQuery.js에서 필요한 쿼리문 작성

<br/>

## 📍 기타 사항

postQuery에서 게시글 기능 구현에 필요한 posts 외의 다른 테이블을 조회하는 쿼리문도 postQuery 파일 안에 모두 포함시켰습니다!
예를 들어, `exports.getLinksByPostId = "SELECT * FROM links WHERE post_id =?";` 이 코드는 links 테이블을 조회하지만, 게시글 기능을 위해 필요한 쿼리문이기 때문에 postQuery.js 안에 포함시켰습니다.

<br/>

2024-05-18 07:00 UTC, JIMIN1020 requested changes

2024-05-18 07:00 UTC, JIMIN1020 commented on services/postService.js
> +    console.log(query);
저는 이 부분은 요청값 핸들링 하는 부분이라 controller에 있어야 한다고 생각합니다! 서비스에는 완성된 최종 쿼리문이랑 데이터만 넘겨주도록 하면 좋을 것 같아요

2024-05-18 07:00 UTC, JIMIN1020 commented on services/postService.js
> +        );
작성자 조회하는 게 여러 곳에서 반복되는데 이건 제가 프로필 조회 모듈 하나 만들어서 모듈화하겠습니다!

2024-05-18 07:02 UTC, kkang0 commented on services/postService.js
> +    console.log(query);
네 알겠습니다!

2024-05-18 07:03 UTC, kkang0 commented on services/postService.js
> +        );
좋아요 감사합니다!

2024-05-18 07:04 UTC, JIMIN1020 commented on services/postService.js
> +    console.log(query);
수정하고 push해주세요~!!

2024-05-18 07:12 UTC, kkang0 commented on services/postService.js
> +    console.log(query);
현재 이 브랜치에 푸시하면 될까요?

2024-05-18 07:13 UTC, JIMIN1020 commented on services/postService.js
> +    console.log(query);
네! 똑같이 푸시하시면 적용됩니다!!

2024-05-27 08:23 UTC, kkang0 commented on services/postService.js
> +    console.log(query);
게시글 조회 분리해서 푸시했습니다!

2024-05-27 08:35 UTC, JIMIN1020 approved these changes

2024-05-27 08:44 UTC, merged